sudo: required
language: go
  go:
  - "1.10"

services:
  - docker
os:
- linux

before_script:
- docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWD}"
- ls
- ./kubernetes/install.sh

script:
- . kubernetes/instal.sh
