sudo: required

services:
  - docker

os:
- linux

before_script:
- docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWD}"
- ls kubernetes
- kubernetes/install.sh

script:
- kubernetes/rolling-update.sh
