baseURL = "/"
languageCode = "pt-BR"
title = "Cloud Native Blog"
theme = "kube"
description = "Este é um blog para falar de assuntos relacionados sobre aplicações Cloud Native"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "cpanato"
  github = "cpanato"
  twitter = "comedordexis"
  email = "ctadeu@gmail.com"
  googleAnalytics = "UA-119150077-1"


[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
